### PR TITLE
fix: close/open blocks

### LINKED ISSUE #1490: Can't collapse blocks (ALPHA.RTC.1 - Local DB)
**Problem**
When using the new ALPHA.RTC.1 with a local DB, I can't collapse any block.
Clic on the arrow won't do anything.

**Athens Version**
1.0.0-ALPHA.RTC.1 - Intel OSX

### PR DESCRIPTION
**Pull request by juniusfree**
fix #1490

### CODE REVIEW

File: src/cljs/athens/events.cljs [hunk 1]
```diff
@@ -1544,14 +1544,14 @@
 
 (reg-event-fx
   :block/open
-  (fn [_ [_ {:keys [block-uid open-block?] :as args}]]
+  (fn [_ [_ {:keys [block-uid open?] :as args}]]
```
Comment (neotyk) [inline src/cljs/athens/events.cljs:1547]: Good catch

**Review by neotyk — APPROVED** [review]
👍
