### PR TITLE
fix(athena): escape special chars in search input and title

### LINKED ISSUE #301: Athena Regex issues
Athena/Athens has some issues when you enter any unterminated regex special characters `[`, `(` into the text input.

**Problem**

The main issue is when you try to navigate to a page that has an unterminated `[`, `(` in the title. The entire page freezes and doesn't render anything.
Entering special characters like `[`, `(` in Athena and trying to create a new page also has some weird behavior. Depending on the combination of characters, Athena doesn't display the page creation button, or the page is created but with some characters missing.

**Expected Behavior**

@nthd3gr33 tested the behavior on Roam and there are no issues with navigating to pages with unterminated `[`, `(` characters in the title.
* Navigating to a page that has `[`, `(` in the title should not freeze the whole page.
* Entering these characters into Athena should not cause Athena to freeze and/or should create the page with all the input characters.

**Dependencies**

- Athens: Latest Master
- browser: Firefox, Edge, Chrome

**To Reproduce**

For Page Creation issue - 
1. Open Athena
2. Enter search text that has unterminated `[`, `(` characters. For example - `Athens [(`. And try to create the page

For Page Freezing issue - 
1. Load the Test Data
2. Open Athena
3. Search for "Athens" and click on the result "Athens [ATH" in the search results
4. Page should freeze

**Screenshots**

https://www.loom.com/share/725a748a7d90433dae55faa10b92af28

image

### PR DESCRIPTION
**Pull request by itsrainingmani**
This PR closes #301 

* create util function for escaping all regexp special characters in a given string

* escape the title in Linked and Unlinked references.

* escape the query in re-case-insensitive

Co-authored-by: nthd3gr33

### CODE REVIEW

File: src/cljs/athens/util.cljs [hunk 1]
```diff
@@ -92,3 +92,16 @@
...
+(def regex-esc-char-map
+  (let [esc-chars "()*&^%$#![]"]
+    (zipmap esc-chars
+            (map #(str "\\" %) esc-chars))))
+
+
+(defn escape-str
+  "Take a string and escape all regex special characters in it"
+  [str]
+  (string/escape str regex-esc-char-map))
```
Comment (tangjeff0) [inline src/cljs/athens/util.cljs:107]: Just a FYI, Clj is both nice and not nice because you can shadow/override clojure.core symbols. In this closure, you are shadowing `str` with an input parameter, so if you tried to use `str` the clojure.core function like `(str "hello" "world")` you would get a function invocation error.

Comment (tangjeff0) [reply src/cljs/athens/util.cljs:107]: I had some difficulty tracking some bugs in `keybindings` because I bound a variable with the symbol `key`, which is also a clojure.core function!
