### PR TITLE
fix: block title is not parsed

### LINKED ISSUE #659: The title is not parsed.
**Problem**

The title is not parsed. 

**Screenshots/Demo**

image
image

**Athens Version**
1.0.0.40-BETA.40

### PR DESCRIPTION
**Pull request by juniusfree**
fix #659
image

Also fixed these related issues:
- overlapping content when editing the block title
athens-659

- unparsed breadcrumb on the block page
image

fixed:
image

### CODE REVIEW

**Comment by juniusfree** [comment]
Added parse to the following:

1. Node title
athens-660-node

(An error occurs for this one after editing the node title. I'll investigate later)

2. Sidebar title
image

3. Athena search result
image

4. Inline search
image

**Comment by tangjeff0** [comment]
I love how you are thinking about the other places where strings are rendered @juniusfree.

Aside from the code implementation, we should also think from the product perspective of _should_ we always format the text.

In the two images below, Roam doesn't format the text in inline search or in Athena.


image

image

**Comment by juniusfree** [comment]
@tangjeff0 That's interesting. I was thinking that it's better if the blocks and page should be displayed consistently across the system.

**Comment by juniusfree** [comment]
Reverted the changes to Athena and inline search.

**Review by tangjeff0 — CHANGES_REQUESTED** [review]
I'm getting this error when trying to type something. Not sure why. Can't find any changes to your use of buttons 
image

**Comment by juniusfree** [comment]
I'll check

**Comment by juniusfree** [comment]
@tangjeff0

I fixed the issue above
image

**Comment by juniusfree** [comment]
@tangjeff0 

The issue above is fixed.
image

File: src/cljs/athens/views/node_page.cljs [hunk 1]
```diff
@@ -527,8 +521,15 @@
...
-          ;;(parse-renderer/parse-and-render title uid)]
+          (when-not timeline-page?
+            [autosize/textarea
+             {:value         (:title/local @state)
+              :id            (str "editable-uid-" uid)
+              :class         (when (= editing-uid uid) "is-editing")
+              :on-blur       (fn [_] (handle-blur node state linked-refs))
+              :on-key-down   (fn [e] (handle-key-down e uid state children))
+              :on-change     (fn [e] (handle-change e state))}])
+          [parse-renderer/parse-and-render (:title/local @state) uid]]
```
Comment (tangjeff0) [inline src/cljs/athens/views/node_page.cljs:532]: Why does the location of this snippet need to change?

File: src/cljs/athens/views/node_page.cljs [hunk 2]
```diff
@@ -505,17 +505,11 @@
          [:h1 (use-style title-style
                          {:data-uid uid
                           :class    "page-header"
-                          :on-click (fn [e] (navigate-uid uid e))})
+                          :on-click (fn [e]
+                                      (.. e preventDefault)
+                                      (dispatch [:editing/uid uid]))})
```
Comment (tangjeff0) [inline src/cljs/athens/views/node_page.cljs:510]: So I agree we want to start editing the textarea when we click on the h1. However, I'm pretty sure `:editing/uid` is not actually used in any way for node pages. Not big deal either way.

More importantly, this change no longer lets the user navigate to a date page when they are on Daily Notes. Perhaps the `:on-click` handler should have an `if` statement for Daily Notes?

**Review by tangjeff0 — CHANGES_REQUESTED** [review]

File: src/cljs/athens/views/node_page.cljs (hunk 1 above)
Comment (juniusfree) [reply src/cljs/athens/views/node_page.cljs:532]: The h1 and textarea input should be adjacent to each other that's why I moved this down. I'm not entirely sure why that's the case but I'm guessing it's the z-index on css.

File: src/cljs/athens/views/node_page.cljs (hunk 2 above)
Comment (juniusfree) [reply src/cljs/athens/views/node_page.cljs]: Fixed the issue with Daily Notes.

Sorry, I just need to clarify. When you say `:editing/uid` is not used for the node page, why does the node page subscribe to it?

Comment (tangjeff0) [reply src/cljs/athens/views/node_page.cljs]: I wasn't sure when I first created node page whether or not it needed `:editing/uid`. Arguably, it could use it.

The purpose of `:editing/uid` is to let the component know whether it is focused or not. This is more useful for blocks, where the caret could be moved to another block. Enter, backspace, up and down arrows are all places that could update :editing/uid.

In the case of block-page and node-page, a user might go to a child block if they press enter on the header (I believe this might've actually been your first PR!).

Arguably, pressing backspace on the 0th child block should take you user's focus back to the title page. Roam doesn't do this, but Notion does do this.

However, it's not super obvious node-page and block-page actually need this anymore. Maybe that would be code to remove in another PR.

**Review by tangjeff0 — APPROVED** [review]

File: src/cljs/athens/views/node_page.cljs (hunk 2 above)
Comment (juniusfree) [reply src/cljs/athens/views/node_page.cljs]: So far, what I found is that `:editing/uid` is used to check whether to apply `is-editing` css class. I might try to investigate more later.

Thanks for the feedback.
