### PR TITLE
fix(parser, blocks): fixed incorrect parser outputs and added non-existent pages auto-create 

### LINKED ISSUE #5: Parse nested links
[Instaparse](https://github.com/Engelberg/instaparse) is the parsing library Athens and Roam use. 

The code for Athens's parser can be found in `src/cljs/athens/parser.cljs`

I watched these [videos](https://www.youtube.com/watch?v=MMxMeX5emUA&list=PLWi7UcbOD_0uAqjcezZxsbSaYwuMSAKxM&index=2&t=4s) to learn about EBNF Syntax, the parsing syntax used by Instaparse.

This [blog](https://adereth.github.io/blog/2016/01/20/visualizing-girl-talk-with-clojure-and-d3-dot-js/) shows an example of `instaparse` that might be helpful for the link parsing.

There are many useful test cases for parsing at http://localhost:3000/#/page/fxi42G2zA, which is the, the page [[Nested [[Links]]]]

## Nested links
Screen Shot 2020-04-27 at 10 59 09 AM

### PR DESCRIPTION
**Pull request by HaojiXu**
(This is my first pull request, so if I'm doing anything wrong style-wise don't hesitate to let me know!)
# Changes in this pull request: 
* the parser now correctly identifies nested page links and multiple page links in one block. For example:
```
user=> (athens.parser/parse-to-ast "[[Hello [[Bruh]] ]] [[World]]")
[:block [:page-link "Hello " [:page-link "Bruh"] " "] " " [:page-link "World"]]
```
* non-existent pages linked in blocks would now be automatically created (including multiple nested pages!).

Partially fixes #5 

# Next steps:
* nested page rendering currenty doesn't work. We need to fix the front-end to make it look like Roam.
* if the user deletes the references to empty pages, these pages won't disappear automatically. We can survey the database and delete anything without references and without block content (i.e. orphan pages).

(Edit: fixed markdown formatting for this thread.)

### CODE REVIEW

File: src/cljs/athens/views/blocks.cljs [hunk 1]
```diff
@@ -341,13 +353,13 @@
...
-                                         (merge {} (when (= index i) inline-selected-search-option))
-                                         {:on-click #(prn "expand")})
-                                  (or title string)])]))}])))
+                             [:<>
+                              (for [[i {:keys [node/title block/string block/uid]}] (map-indexed list results)]
+                                ^{:key (str "inline-search-item" uid)}
+                                [:div (use-style
+                                       (merge {} (when (= index i) inline-selected-search-option))
+                                       {:on-click #(prn "expand")})
+                                 (or title string)])]))}])))
```
Comment (tangjeff0) [inline src/cljs/athens/views/blocks.cljs]: Lots of indentation diffs in this PR. Do you know what's going on?

File: src/cljs/athens/views/blocks.cljs [hunk 2]
```diff
@@ -221,7 +224,16 @@
 (defn on-change
   [value uid]
   ;; (prn "ONCHANGE" value)
-  (dispatch [:transact [{:db/id [:block/uid uid] :block/string value :edit/time (now-ts)}]]))
+  (dispatch [:transact [{:db/id [:block/uid uid] :block/string value :edit/time (now-ts)}]])
+  ;; automatically add non-existent pages
+  ;; TODO: delete pages that are no longer connected to anything else
+  (parse/transform {:page-link (fn [& title]
+                                 (if-not (db/search-exact-node-title (apply + title)) (let [uid (gen-block-uid)]
```
Comment (tangjeff0) [inline src/cljs/athens/views/blocks.cljs:231]: This is a formatting thing: let the `then` and `else` clauses be separate lines. It also be clearer to flip the clauses and use normal `if`.

Comment (tangjeff0) [reply src/cljs/athens/views/blocks.cljs:231]: I'm not sure how I feel about the page creation happening here, but fine to have it here for now.

Comment (tangjeff0) [reply src/cljs/athens/views/blocks.cljs:231]: Can you explain the usage of `+ apply` to me? If it is because `title` comes in as a list with ` & title`, I would first like greater clarity or comments on why we use `&` in the first place.

File: src/cljs/athens/views/blocks.cljs [hunk 3]
```diff
@@ -221,7 +224,16 @@
...
+                                                                                        (d/transact! db/dsdb [{:node/title     (str apply + title)
```
Comment (tangjeff0) [inline src/cljs/athens/views/blocks.cljs:232]: Should use `(dispatch [:transact])` pattern like above.

File: src/cljs/athens/views/blocks.cljs (hunk 1 above)
Comment (HaojiXu) [reply src/cljs/athens/views/blocks.cljs]: Yes - the vscode prettifier doesn't follow the cljstyle standards, so I fixed it in the 4th commit

File: src/cljs/athens/views/blocks.cljs (hunk 2 above)
Comment (HaojiXu) [reply src/cljs/athens/views/blocks.cljs:231]: I agree that we should have some further discussion about where to process the new page creation/deletion logic. But I think it's more of a performance issue so we could just have the functionality now and talk about it later :)

Comment (HaojiXu) [reply src/cljs/athens/views/blocks.cljs:231]: regarding the `+ apply` issue, because the nested page-link is processed recursively, `parse/transform` performs a leaf-first search which creates the page and returns the "unparsed" value of the `:page-link` node. For example, parsing `[[A[[B]]]]` would create a page named `B` but also returns `[[B]]` for its parent node to create (`A[[B]]`). `+ apply` is used to combine the list of children strings to the actual page name (a unique transformation).

File: src/cljs/athens/views/blocks.cljs (hunk 3 above)
Comment (HaojiXu) [reply src/cljs/athens/views/blocks.cljs:232]: Fixed!

File: src/cljs/athens/parse_renderer.cljs [hunk 4]
```diff
@@ -63,35 +74,30 @@
...
+                 [:img (use-style image {:class "url-image"
+                                         :alt   alt
+                                         :src   url})])
+    :url-link  (fn [{url :url} text]
+                 [:a (use-style url-link {:class "url-link"
+                                          :href  url})
+                  text])
+    :bold      (fn [text]
+                 [:strong {:class "contents bold"} text])}
+   tree))
```
Comment (tangjeff0) [inline src/cljs/athens/parse_renderer.cljs:100]: Unnecessary whitespace changes

File: src/cljs/athens/views/blocks.cljs (hunk 2 above)
Comment (tangjeff0) [reply src/cljs/athens/views/blocks.cljs]: Wow, pretty technical issue explained pretty well!

Comment (tangjeff0) [reply src/cljs/athens/views/blocks.cljs]: Also please let me resolve the comments going forward, I had to find and open this to find your response :)

File: src/cljs/athens/parse_renderer.cljs (hunk 4 above)
Comment (HaojiXu) [reply src/cljs/athens/parse_renderer.cljs]: Fixed!

File: src/cljs/athens/views/blocks.cljs [hunk 5]
```diff
@@ -221,7 +223,18 @@
...
+  ;; automatically add non-existent pages
+  ;; TODO: delete pages that are no longer connected to anything else
+  (parse/transform {:page-link (fn [& title]
+                                 (if (nil? (db/search-exact-node-title (apply + title)))
+                                   (let [uid (gen-block-uid)]
+                                     (dispatch [:transact [{:node/title     (apply + title)
+                                                            :block/uid      (str uid)
+                                                            :edit/time      (now-ts)
+                                                            :create/time    (now-ts)}]]))
+                                   nil)
```
Comment (tangjeff0) [inline src/cljs/athens/views/blocks.cljs:236]: `if` statement with a `nil` for the else clause should just use `when`

File: src/cljs/athens/views/blocks.cljs [hunk 6]
```diff
@@ -221,7 +223,18 @@
...
+  (dispatch [:transact [{:db/id [:block/uid uid] :block/string value :edit/time (now-ts)}]])
+  ;; automatically add non-existent pages
+  ;; TODO: delete pages that are no longer connected to anything else
+  (parse/transform {:page-link (fn [& title]
+                                 (if (nil? (db/search-exact-node-title (apply + title)))
+                                   (let [uid (gen-block-uid)]
+                                     (dispatch [:transact [{:node/title     (apply + title)
+                                                            :block/uid      (str uid)
+                                                            :edit/time      (now-ts)
+                                                            :create/time    (now-ts)}]]))
```
Comment (tangjeff0) [inline src/cljs/athens/views/blocks.cljs:235]: `(now-ts)` will have two different values when they should be the same value. Define it once in the `let` binding and use in both attributes.

File: src/cljs/athens/views/blocks.cljs [hunk 7]
```diff
@@ -221,7 +223,18 @@
...
   ;; (prn "ONCHANGE" value)
-  (dispatch [:transact [{:db/id [:block/uid uid] :block/string value :edit/time (now-ts)}]]))
+  (dispatch [:transact [{:db/id [:block/uid uid] :block/string value :edit/time (now-ts)}]])
+  ;; automatically add non-existent pages
+  ;; TODO: delete pages that are no longer connected to anything else
+  (parse/transform {:page-link (fn [& title]
+                                 (if (nil? (db/search-exact-node-title (apply + title)))
+                                   (let [uid (gen-block-uid)]
+                                     (dispatch [:transact [{:node/title     (apply + title)
+                                                            :block/uid      (str uid)
```
Comment (tangjeff0) [inline src/cljs/athens/views/blocks.cljs:233]: `uid` is already a string.

File: src/cljs/athens/views/blocks.cljs [hunk 8]
```diff
@@ -221,7 +223,18 @@
...
   [value uid]
   ;; (prn "ONCHANGE" value)
-  (dispatch [:transact [{:db/id [:block/uid uid] :block/string value :edit/time (now-ts)}]]))
+  (dispatch [:transact [{:db/id [:block/uid uid] :block/string value :edit/time (now-ts)}]])
+  ;; automatically add non-existent pages
+  ;; TODO: delete pages that are no longer connected to anything else
+  (parse/transform {:page-link (fn [& title]
+                                 (if (nil? (db/search-exact-node-title (apply + title)))
+                                   (let [uid (gen-block-uid)]
+                                     (dispatch [:transact [{:node/title     (apply + title)
```
Comment (tangjeff0) [inline src/cljs/athens/views/blocks.cljs:232]: If you're going to use `(apply + title)` up to three times, I'd just define it in a `let` binding at the top-level.

Comment (HaojiXu) [reply src/cljs/athens/views/blocks.cljs:232]: Fixed

File: src/cljs/athens/views/blocks.cljs (hunk 7 above)
Comment (HaojiXu) [reply src/cljs/athens/views/blocks.cljs:233]: Fixed

File: src/cljs/athens/views/blocks.cljs (hunk 6 above)
Comment (HaojiXu) [reply src/cljs/athens/views/blocks.cljs:235]: Fixed

File: src/cljs/athens/views/blocks.cljs (hunk 5 above)
Comment (HaojiXu) [reply src/cljs/athens/views/blocks.cljs:236]: Fixed

**Comment by HaojiXu** [comment]
Thank you @tangjeff0 for your patience! I sure will write more standardized code in my later commits :)
