### PR TITLE
fix: closes #11

### LINKED ISSUE #11: Refreshing Athens on a non-root page causes app to freezes
Non-root page example: `#/page/AVOHMK6bK`

My guess for why this is is that when the app is mounting, the datoms have not yet been loaded from Github. The solution would probably be to show a loading UI, and let all datascript queries wait in a queue until the datoms have been loaded.

### PR DESCRIPTION
**Pull request by tangjeff0**
closes #11 

Uses `day8.re-frame.async-flow-fx`

### CODE REVIEW

File: src/cljs/athens/views.cljs [hunk 1]
```diff
@@ -68,12 +68,15 @@
...
-      [:div
-       [alert]
-       ;;[:h1 (str "Hello World")]
-       [:div
-        [:a {:href (rfee/href :pages)} "All /pages"]
-        [:span {:style {:margin 0 :margin-left 10}} "Current Route: " [:b (-> @current-route :path)]]]
-       [match-panel (-> @current-route :data :name)]])))
+      [alert]
+      (if @loading
+        [:h4 "Loading... (at least it'll be faster than Roam)"]
```
Comment (jeroenvandijk) [inline src/cljs/athens/views.cljs:76]: 🤣 🤣 🤣 🤣 🤣
