### PR TITLE
fix: broadcast username on update

### LINKED ISSUE #1514: Username change not updated (1.0.0-ALPHA.RTC.1 - Remote DB)
**Problem**
When I change my username in the settings, it won't be updated (for me and for every other user of the remote DB) until I disconnect then reconnect on the remote DB.

**Athens Version**
1.0.0-ALPHA.RTC.1 - Intel OSX

### PR DESCRIPTION
**Pull request by juniusfree**
- This PR fixes #1514.
- This will now allow the username to be updated to every client in the lan-party when one of the clients updated the user name.
- A new event to send the new user is created in the presence module on the client-side. This event will be triggered when the username on the settings page is updated.
- A new event is added on the server-side to broadcast the new user name.
- On the server-side, the atom, `athens.self-hosted.clients/clients` is also updated when the user name is changed. This is to ensure that the newly connected clients will get the latest list of user names.
- ~~On the server-side, I'm also thinking if the `editing-handler` and `username-handler` can be generalized but I'm unsure yet on how to do it.~~

### CODE REVIEW

File: src/clj/athens/self_hosted/web/presence.clj [hunk 1]
```diff
@@ -18,6 +18,7 @@
 (def supported-event-types
   #{:presence/hello
     :presence/editing
+    :presence/username
```
Comment (neotyk) [inline src/clj/athens/self_hosted/web/presence.clj:21]: `rename` might be a better name here.

File: src/clj/athens/self_hosted/web/presence.clj [hunk 2]
```diff
@@ -58,6 +59,21 @@
...
+  [datahike channel {:event/keys [id args]}]
+  (let [{:keys
+         [current-username
+          new-username]}         args
+        max-tx                   (:max-tx @datahike)
+        broadcast-username-event (common-events/build-presence-broadcast-username-event max-tx
+                                                                                        current-username
+                                                                                        new-username)]
+
+    (clients/add-client! channel new-username)
```
Comment (neotyk) [inline src/clj/athens/self_hosted/web/presence.clj:72]: should we be adding a client?
This client already exists and it's renaming.

**Review by neotyk — CHANGES_REQUESTED** [review]
2 comments, 1st about naming, 2nd about actual usage in backend.

File: src/clj/athens/self_hosted/web/presence.clj (hunk 2 above)
Comment (juniusfree) [reply src/clj/athens/self_hosted/web/presence.clj:72]: It works but the function should be renamed.

**Comment by juniusfree** [comment]
Other todos but not for this PR:
1. rename `clients/add-client!` function
2. consider how renaming will handle failures (e.g. name clash with other clients, server failure)

File: src/clj/athens/self_hosted/web/presence.clj (hunk 1 above)
Comment (juniusfree) [reply src/clj/athens/self_hosted/web/presence.clj]: Updated to `rename`
