### PR TITLE
fix(selection): nested opacities for shift+up/down, shift+click, and mousedown+mouseenter

### LINKED ISSUE #326: fix(selection): Show proper selection opacity for nested blocks #241
**Feature Issue**: #241 

**Screenshot**

Screen Shot 2020-08-11 at 3 24 05 PM

**Steps**

- use [`goog.dom.findCommonAncestor`](https://github.com/google/closure-library/blob/master/closure/goog/dom/dom.js#L1693)
- update `:selected/items` in re-frame db

### PR DESCRIPTION
**Pull request by tangjeff0**
- fixes #326 for shift+up/down, shift+click, and mousedown+mouseenter
- fixes bug where drag and drop with selected text in textarea crashes app
- UI: comments out `hover` and `is-editing` opacities, to make selected blocks easier
- TODO: some behavior for indent, cut, and backspace when multi-selected blocks (especially indexing, order)
- TODO: reorganize blocks and listeners

### CODE REVIEW

File: src/cljs/athens/keybindings.cljs [hunk 1]
```diff
@@ -222,7 +222,7 @@
               (or (and up? top-row?)
                   (and down? bottom-row?)) (do
                                              (.. target blur)
-                                             (dispatch [:editing/uid nil])
+                                             ;;(dispatch [:editing/uid nil])
```
Comment (tangjeff0) [inline src/cljs/athens/keybindings.cljs:225]: rm

File: src/cljs/athens/listeners.cljs [hunk 2]
```diff
@@ -42,49 +42,19 @@
...
-  [_]
-  (events/unlisten js/window EventType.MOUSEOVER multi-block-select-over)
-  (events/unlisten js/window EventType.MOUSEUP multi-block-select-up))
-
 ;; -- When user clicks elsewhere -----------------------------------------
 
 (defn unfocus
   [e]
-  (let [selected-items @(subscribe [:selected/items])
+  (let [selected-items? (boolean @(subscribe [:selected/items]))
```
Comment (tangjeff0) [inline src/cljs/athens/listeners.cljs:49]: Is always true. Must use `empty?`

Comment (tangjeff0) [reply src/cljs/athens/listeners.cljs:49]: Comment on `when` conditions in natural language

File: src/cljs/athens/listeners.cljs [hunk 3]
```diff
@@ -166,7 +136,7 @@
 (defn init
   []
   ;; (events/listen js/window EventType.MOUSEDOWN edit-block)
-  (events/listen js/window EventType.CLICK unfocus)
+  (events/listen js/document EventType.MOUSEDOWN unfocus)
   (events/listen js/window EventType.CLICK click-outside-athena)
   (events/listen js/window EventType.KEYDOWN multi-block-selection)
   (events/listen js/window EventType.KEYDOWN key-down)
```
Comment (tangjeff0) [inline src/cljs/athens/listeners.cljs:142]: When do we we use `document` and when `window`?

File: src/cljs/athens/views/blocks.cljs [hunk 4]
```diff
@@ -515,49 +515,112 @@
...
+  • 1 source
+  • 2
+   • 3 target
+  This basically means there is no direct path from 1 to 3 using select/up or select/down, because the parent gets selected, not the block.
+
+  This is really the same edge case: there isn't a direct path with select/up or select/down.
+
+  If n is a child of n-1"
+  ;; delta is maximum iterations. if end condition is not met within delta iterations, terminate
+  ;; if
```
Comment (tangjeff0) [inline src/cljs/athens/views/blocks.cljs:533]: - finish docstrings/comments
- come up with better name

File: src/cljs/athens/views/blocks.cljs [hunk 5]
```diff
@@ -515,49 +515,112 @@
...
+        blocks (->> (.. page (querySelectorAll ".block-container"))
+                    array-seq
+                    vec)
+        uids (map get-dataset-uid blocks)
+        start-idx (first (keep-indexed (fn [i uid] (when (= uid source-uid) i)) uids))
+        end-idx   (first (keep-indexed (fn [i uid] (when (= uid target-uid) i)) uids))]
+    (when (and start-idx end-idx)
+      (let [up? (> start-idx end-idx)
+            delta (js/Math.abs (- start-idx end-idx))
+            select-f  (if up? athens.events/select-up athens.events/select-down)
```
Comment (tangjeff0) [inline src/cljs/athens/views/blocks.cljs:546]: import?

File: src/cljs/athens/views/blocks.cljs [hunk 6]
```diff
@@ -515,49 +515,112 @@
...
-          (let [selected-blocks (subvec blocks start (inc end))
-                selected-uids (mapv #(.. % -dataset -uid) selected-blocks)]
-            (dispatch [:editing/uid nil])
-            (dispatch [:selected/add-items selected-uids])))))))
+    (when (and source-uid target-uid (not= source-uid target-uid) (.. e -shiftKey))
+      (distance-f e source-uid target-uid))))
+
+
+(defn up-fn
+  ""
```
Comment (tangjeff0) [inline src/cljs/athens/views/blocks.cljs:573]: Finish comments for all of these

File: src/cljs/athens/views/blocks.cljs [hunk 7]
```diff
@@ -753,15 +819,18 @@
...
+                           (when is-editing "is-editing")
+                           (when is-selected "is-selected")
+                           (when (and (seq children) open) "show-tree-indicator")]
+          :data-uid       uid
+          :on-drag-over   (fn [e] (block-drag-over e block state))
+          :on-drag-leave  (fn [e] (block-drag-leave e block state))
+          :on-drop        (fn [e] (block-drop e block state))}
+          ;;:on-mouse-enter (fn [e] (textarea-mouse-enter e block state))
+          ;;:on-mouse-leave (fn [e] (textarea-mouse-leave e block state))
+          ;;:on-mouse-down  (fn [e] (textarea-mouse-down e uid state))}
```
Comment (tangjeff0) [inline src/cljs/athens/views/blocks.cljs:833]: rm
